# This file tells YOLOv8 where to find your dataset & what classes it’s detecting

# Train images
train: /kaggle/input/medical-image-dataset-brain-tumor-detection/BrainTumor/BrainTumorYolov8/train/images

# Validation images
val: /kaggle/input/medical-image-dataset-brain-tumor-detection/BrainTumor/BrainTumorYolov8/valid/images
test: /kaggle/input/medical-image-dataset-brain-tumor-detection/BrainTumor/BrainTumorYolov8/test/images

# Validation images
nc: 3

# Class names
names: ['glioma', 'meningioma', 'pituitary']
